### PR TITLE
Bump up all dependencies

### PR DESCRIPTION
**Pull request by jupyterkat**
no other changes of note

### CODE REVIEW

**Comment by SpaceManiac** [comment]
Any particular motive?

I'm not excited to accept this as-is because even in a skim I see various line wrappings/unwrappings that rustfmt does that straight up make the code less readable. I'd have to spend time to sit down with it to figure out how to make it not touch those.

**Comment by jupyterkat** [comment]
It autoformats your code, for spending less time pressing tabs and enters. And it makes the code more readable most of the time. Only in some cases like the fast table fmt that it screws up.

**Comment by willox** [comment]
This always annoyed me when working on SpacemanDMM stuff since, like many other Rust coders, I just throw shit at the wall and format afterwards

Can't do that here since it changes unrelated code :)

**Comment by jupyterkat** [comment]
those one offs can be easily fixed with an attribute y'know

**Comment by SpaceManiac** [comment]
Having seriously attempted it, this diff is too big to review. I'm happy to accept just the dependency upgrades if you can tolerate separating them out from this PR, but I will rustfmt the project myself if and when I am convinced about it.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
