### PR TITLE
Fold sdmm parser into the repo

### PR DESCRIPTION
**Pull request by spookydonut**
this is useful and it'd be great to keep it updated.

### CODE REVIEW

**Comment by SpaceManiac** [comment]
Releases already include 4 different binaries. I'm not sure I want to make that number bigger.

**Comment by skull132** [comment]
> 
> 
> Releases already include 4 different binaries. I'm not sure I want to make that number bigger.

IMO this is a relatively useful binary to have, as it allows SDMM to be applied to other processes relatively easily. I already have plans to automate certain wiki articles with this, and someone from CM wanted a tool like this to be used for balancing.

If binary bloat is the issue, then why not consider rolling some of these into a single binary that is switchable, ala git?

**Comment by SpaceManiac** [comment]
> If binary bloat is the issue, then why not consider rolling some of these into a single binary that is switchable, ala git?

What are our main consumers?
- MapDiffBot and AA's webmap, using dmm-tools compiled from source (sometimes modified)
- Travis, using dmdoc and dreamchecker downloaded from GitHub releases
- VSC extension, using langserver downloaded from private infrastructure

That covers the four binaries that currently matter. langserver and dmm-tools are made available on GitHub releases for completeness. Where can we make this fit? If we rearranged existing binaries, what would we combine?

The main force in the opposite direction of bundling is the difference in dependency sets between the different components, which manifests in build time and in file size.

**Comment by spookydonut** [comment]
strongdmm has been updated.

**Pull request closed without merging**
