### PR TITLE
Fix detection of ambig ternary in operations

### LINKED ISSUE #122: Ternary has precedence over BinaryOp::In
`(foo ? foo : 2 in L)`
byond parses this as
`((foo ? foo : 2) in L)`
but we parse it as
`(foo ? foo : (2 in L))`
```
BinaryOp {
    op: In,
    lhs: Base {
        unary: [],
        term: Spanned {
            location: Location {
                file: FileId(
                    2,
                ),
                line: 22,
                column: 15,
            },
            elem: Int(
                2,
            ),
        },
        follow: [],
    },
    rhs: Base {
        unary: [],
        term: Spanned {
            location: Location {
                file: FileId(
                    2,
                ),
                line: 22,
                column: 20,
            },
            elem: Ident(
                "L",
            ),
        },
        follow: [],
    },
}
```

### PR DESCRIPTION
**Pull request by spookydonut**
Related #122

### CODE REVIEW

**Comment by SpaceManiac** [comment]
Isn't the issue that the parser produces the wrong output?

Seems like the original detection code would work if the parser was fixed.

Alternatively, checking if `?:` contains an `in` on its right-hand could just as well happen in dreamchecker as the parser.

**Comment by SpaceManiac** [comment]
I think I'd rather fix the parser's output than hack the diagnostic

**Comment by spookydonut** [comment]
> 
> 
> I think I'd rather fix the parser's output than hack the diagnostic

I didn't see a trivial way to do that.

**Comment by SpaceManiac** [comment]
the bug can stand while we stew on a solution

**Pull request closed without merging**
